# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Test and build with ant

on:
  push:
    branches:
      - master
      - dev/pitc-*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
            # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml build
      - name: Test with Ant
        run: ant -noinput -buildfile build.xml test
      - name: Upload datasource test output file
        uses: actions/upload-artifact@v2
        with:
          name: datasource-test.txt
          path: ${{ github.workspace}}/tmp/datasource-test.txt
      - name: Upload test output file
        uses: actions/upload-artifact@v2
        with:
         name: jdbc-tests.txt
         path: ${{ github.workspace }}/tmp/jdbc-tests.txt
